### ISSUE TITLE
I can not install with composer

### ISSUE THREAD

**Issue by JacquesMarques** [yiibr/yii2-br-validator#8]
Hi,
When I try install in my machine I receive this menssages:

php composer.phar require --prefer-dist yiibr/yii2-br-validator "*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package yiibr/yii2-br-validator could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by leandrogehlen** [comment]
This occurs because, there is no a release version. I generated the release version `1.0.0` and i believe that will fix the issue.

**Comment by JacquesMarques** [comment]
Now work fine, thanks.
